# Generated by Django 3.2.4 on 2021-07-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio_eletronico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'pedido', 'verbose_name_plural': 'pedidos'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'produto', 'verbose_name_plural': 'produtos'},
        ),
        migrations.AlterField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(db_table='itens_pedido', related_name='itens_pedido', to='comercio_eletronico.Produto'),
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='categoria',
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='pedido',
        ),
        migrations.AlterModelTable(
            name='produto',
            table='produto',
        ),
    ]
